import { Nunito } from 'next/font/google'

import './globals.css'

export const metadata = {
  title: 'Booking Calendar Site',
  description: 'Generated by create next app',
}

const font = Nunito({ 
  subsets: ['latin'], 
});

import Navbar from '@/app/components/navbar/Navbar';
import ClientOnly from '@/app/components/ClientOnly';
import RegisterModal from '@/app/components/modals/RegisterModal';

import ToasterProvider from '@/app/providers/ToasterProvider';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
      
        <ClientOnly>
        <ToasterProvider />
          <RegisterModal/>
          <Navbar/>
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
